DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY (
  id BIGINT IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS AUTHOR;

CREATE TABLE AUTHOR (
  id BIGINT IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(400) NOT NULL,
  nationality VARCHAR(250) NOT NULL
);